<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20240402223323" tests="1" file="unittest/loader.py" time="0.002" timestamp="2024-04-02T22:33:24" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="test_function3_tests" time="0.002" timestamp="2024-04-02T22:33:24">
		<error type="ImportError" message="Failed to import test module: test_function3_tests
Traceback (most recent call last):
  File &quot;/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/Users/natedamstra/PycharmProjects/G88.2024.T06.EG2/src/unittest/python/test_function3_tests.py&quot;, line 5, in &lt;module&gt;
    from src.main.python.uc3m_travel import HotelManagementException
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_function3_tests
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/natedamstra/PycharmProjects/G88.2024.T06.EG2/src/unittest/python/test_function3_tests.py", line 5, in <module>
    from src.main.python.uc3m_travel import HotelManagementException
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
</testsuite>
